apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: acme-corp-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress # matches istio-ingress pods
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
