apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - istio.yaml

images:
  - name: static-app-backend
    newName: 688365519474.dkr.ecr.eu-north-1.amazonaws.com/acme-corp-dev/api
    newTag: 66ce940
